[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "libnirs"
version = "0.6.2"
description = "Library for NIRS analysis"
license = "Proprietary"
authors = ["Julia Tatz <julia.tatz@childrens.harvard.edu>"]
include = ['libnirs/extc.npz']

[tool.poetry.dependencies]
python = ">=3.7"
numpy = ">=1.20"
scipy = ">=1.6"
matplotlib = ">=3.4"
numba = ">=0.53"
numba-scipy = ">=0.3"
xarray = ">=0.18"

[tool.poetry.dev-dependencies]
sympy = ">=1"
